# Generated by Django 5.1.4 on 2025-01-06 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='guidance_scale',
            field=models.FloatField(default=7.5),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='model',
            field=models.CharField(default='stable-diffusion-v1-5', max_length=100),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='n_steps',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='seed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='style',
            field=models.CharField(default='base', max_length=100),
        ),
        migrations.AlterField(
            model_name='imagegenerationrequest',
            name='generated_image',
            field=models.ImageField(default='', upload_to='generated/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagegenerationrequest',
            name='prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imagegenerationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
