# Generated by Django 5.1.4 on 2025-01-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_alter_imagegenerationrequest_generated_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='original_prompt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
