# Generated by Django 5.1.4 on 2025-01-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0004_imagegenerationrequest_original_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='clip_skip',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='denoising_strength',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='height',
            field=models.IntegerField(default=512),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='hires_fix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='negative_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='safety_checker',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='sampler',
            field=models.CharField(default='DPM++ 2M Karras', max_length=50),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='tiling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagegenerationrequest',
            name='width',
            field=models.IntegerField(default=512),
        ),
    ]
