# Generated by Django 5.1.4 on 2025-01-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0006_imagegenerationrequest_color_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='safety_checker',
            field=models.BooleanField(default=True),
        ),
    ]
